//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursprj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komplektsh
    {
        public int id_kompl { get; set; }
        public string name_komplekt { get; set; }
        public int type_komplekt { get; set; }
        public string characterist { get; set; }
        public int id_status { get; set; }
        public Nullable<int> id_pc { get; set; }
    
        public virtual Status Status1 { get; set; }
        public virtual Technika Technika1 { get; set; }
        public virtual Type_Komplekt Type_Komplekt1 { get; set; }
    }
}
