//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursprj2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UchTechEntities : DbContext
    {
        private static UchTechEntities _context;
        public UchTechEntities()
            : base("name=UchTechEntities")
        {
        }
        public static UchTechEntities GetContext()
        {
            if (_context == null)
                _context = new UchTechEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Komplektsh> Komplektsh { get; set; }
        public virtual DbSet<Sotrud> Sotrud { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Technika> Technika { get; set; }
        public virtual DbSet<Type_Techn> Type_Techn { get; set; }
        public virtual DbSet<Type_Komplekt> Type_Komplekt { get; set; }
    }
}
