//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursprj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrud
    {
        public int id_sotr { get; set; }
        public string FIO { get; set; }
        public string dolzh { get; set; }
        public string phone { get; set; }
    
        public virtual Technika Technika { get; set; }
    }
}
