//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursprj2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technika
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technika()
        {
            this.Komplektsh1 = new HashSet<Komplektsh>();
        }
    
        public int id_techn { get; set; }
        public string name { get; set; }
        public string characterstc { get; set; }
        public int id_type_techn { get; set; }
        public Nullable<int> id_sotrud { get; set; }
        public int id_status { get; set; }
    
        public virtual Type_Techn Type_Techn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Komplektsh> Komplektsh1 { get; set; }
        public virtual Sotrud Sotrud1 { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
